BUGFIX: Handle numeric node aggregate ids in `NodeAggregateIds` collection
`fromArray` is not safe and throws when constructed with ["a", "123"]:
> Fatal error: Cannot use positional argument after named argument during unpacking

Because we pass the indexed array as spread to the constructor